### ISSUE TITLE
Course Name Unrecognized Argument

### ISSUE THREAD

**Issue by An0m0ly** [csyezheng/coursera-helper#1]
Fresh install as a docker container.

When executing the command, I receive an Unrecognized Argument when attempting to supply the course name as a slug with accompanying hyphens or also when trying the course name with spaces. It also does not like the video resolution argument, but I omitted this in an attempt to produce a successful execution, but it still produces the error stating that the course name is unrecognized.

Here is my docker command

'coursera-helper' '--cauth' 'key' '--download-quizzes' '--download-notebook' '--about' '--video-resolution 720p' 'foundations-of-digital-marketing-and-e-commerce'

**Comment by ShifuKing** [comment]
hello @csyezheng, 
first of all thank you for your Great work on Coursera Helper. It truly changes a lot of think for me. 

Please while i was dowloading this [course ](https://www.coursera.org/learn/data-analysis-and-visualization-with-power-bi)im facing this following error. Please can you help me? 

This is the error: 
_Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Scripts\coursera-helper.exe\__main__.py", line 7, in <module>
  File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\coursera_dl.py", line 256, in main
    error_occurred, completed = download_class(
                                ^^^^^^^^^^^^^^^
  File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\coursera_dl.py", line 216, in download_class
    return download_on_demand_class(session, args, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\coursera_dl.py", line 172, in download_on_demand_class
    completed = course_downloader.download_modules(modules)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\workflow.py", line 163, in download_modules
    last_update = self._handle_resource(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\workflow.py", line 226, in _handle_resource
    if url.startswith(IN_MEMORY_MARKER):
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'_
