### ISSUE TITLE
Issue with some course While downloading 

### ISSUE THREAD

**Issue by ShifuKing** [csyezheng/coursera-helper#2]
hello @csyezheng,
first of all thank you for your Great work on Coursera Helper. It truly changes a lot of think for me.

Please while i was dowloading this [course ](https://www.coursera.org/learn/data-analysis-and-visualization-with-power-bi)im facing this following error. Please can you help me?

This is the error:
_Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Scripts\coursera-helper.exe_main.py", line 7, in
File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\coursera_dl.py", line 256, in main
error_occurred, completed = download_class(
^^^^^^^^^^^^^^^
File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\coursera_dl.py", line 216, in download_class
return download_on_demand_class(session, args, class_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\coursera_dl.py", line 172, in download_on_demand_class
completed = course_downloader.download_modules(modules)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\workflow.py", line 163, in download_modules
last_update = self._handle_resource(
^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zo\AppData\Local\Programs\Python\Python311\Lib\site-packages\coursera_helper\workflow.py", line 226, in handle_resource
if url.startswith(IN_MEMORY_MARKER):
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by csyezheng** [comment]
@ShifuKing 

This bug has been fixed in version 0.12.3.
Please upgrade coursera-helper by running:
```
python -m pip install --upgrade --index-url https://pypi.org/simple/ coursera-helper
```

Make sure you upgrade to the correct version by running:
```
coursera-helper --version
```

**Comment by nerdorwhatX** [comment]
@csyezheng 

Can you see this kindly? This tool no longer downloads quizzes and notebooks. the logs are given below:

Processing section     quiz
Processing lecture         disease-detection-with-computer-vision (ungradedAssignment)
Unsupported typename "ungradedAssignment" in lecture "disease-detection-with-computer-vision" (lecture id "n6qhq")
Processing section     programming-assignment-chest-x-ray-medical-diagnosis-with-deep-learning
Processing lecture         optional-downloading-your-notebook-downloading-your-workspace-and-refreshing (supplement)
Processing lecture         about-the-autograder (supplement)
Processing lecture         chest-x-ray-medical-diagnosis-with-deep-learning (gradedProgramming)
Error 404 Client Error: Not Found for url: https://api.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/M-45KyN0EeqCgRKukXAJ-Q~L92NM?fields=submissionLearnerSchema getting page https://api.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/M-45KyN0EeqCgRKukXAJ-Q~L92NM?fields=submissionLearnerSchema
The server replied: {"message":"","statusCode":404}
Could not download programming assignment L92NM: 404 Client Error: Not Found for url: https://api.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/M-45KyN0EeqCgRKukXAJ-Q~L92NM?fields=submissionLearnerSchema

**Comment by bmidy** [comment]
Hi All,

Got same Issues, not possible tpo ge the Quizzes and Notebook  downloaded
Videos and subtitles and SLides are OK
